name: Excite
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audio_video_progress_bar: ^0.10.0
  cached_network_image: ^3.2.0
  clay_containers: ^0.3.2
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  flutter_neumorphic: ^3.2.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  http: ^0.13.4
  just_audio: ^0.9.18
  localstorage: ^4.0.0+1
  localstore: ^1.2.1
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  expandable: ^5.0.1
  flutter_typeahead: ^3.2.4
  flutter_keyboard_visibility_web: ^2.0.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/logo/logo.png"
flutter_launcher_name:
  name: "Excite"
flutter_native_splash:
  background_image: assets/logo/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo/splash_logo.png
    - assets/logo/splash.png
    - assets/logo/logo.png
  